#!/bin/bash

# ==================== Voice Web - Installation Program ====================
#
#     This program is an installation software that will automatically
# install all the required softwares for running Voice Web.
#
#     Once the installation process has finished, you can remove this
# installation file, you don't need it anymore.
#
# Contact     : i.a.sebsil83@gmail.com
# Youtube     : https://www.youtube.com/user/IAsebsil83
# GitHub repo : https://github.com/iasebsil83
#
# Let's Code !                                                      By I.A.
# ==========================================================================



# ---- INIT ----

#presentation
clear
echo -e "Welcome in the VoiceWeb installation program.\n"
echo -e "\n[Press ENTER to continue]"
read






# ---- REQUIREMENTS ----

# git
clear
git version &> /dev/null && {
	echo "git already installed."
} || {
	echo "VoiceWeb requires package 'git'."
	echo "Please install it before retrying :"
	echo "    > sudo apt install git"
	echo -e "\n[Installation cancelled]"
	exit 1
}
echo -e "\n[Press ENTER to continue]"
read






# ---- NODE.JS ----

#nvm
clear
if [[ -e nvm ]]; then
	echo "nvm already installed."
else
	echo -e "Creating a local installation of nvm...\n"
	git clone https://github.com/nvm-sh/nvm || {
		echo "Unable to get nvm (from GitHub)."
		echo "Maybe you do have not a correct Internet connection ?"
		echo -e "\n[Installation cancelled]"
		exit 1
	}
	echo -e "\nDone."
fi
echo -e "\n[Press ENTER to continue]"
read

#preparation for the use of nvm
export NVM_DIR="$PWD/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

#nodejs
clear
node --version &> /dev/null && {
	echo "node.js already installed."
} || {
	echo -e "Installing node.js...\n"
	nvm install v12.22.7 || {
		echo "Unable to install node.js (using nvm)."
		echo "Maybe you do not have a correct Internet connection ?"
		echo -e "Trying to use './nvm.sh install node' did not work."
		echo -e "\n[Installation cancelled]"
		exit 1
	}
}
echo -e "\n[Press ENTER to continue]"
read






# ---- NODE MODULES ----

#prepare installation of node modules
mkdir node_modules
cp Project/package.json $PWD #VERY IMPORTANT ! COMPATIBILITY DEPENDS ON THIS FILE ONLY !

#angular
clear
if [[ -e node_modules/.bin/ng ]]; then
	echo "Angular already installed locally."
else
	echo -e "Creating a local installation of Angular...\n"
	npm install @angular/cli && {
		echo -e "\nDone."
	} || {
		echo "Unable to install angular (using npm)."
		echo "Maybe you do not have a correct Internet connection ?"
		echo -e "Trying to use 'npm install @angular/cli' did not work."
		echo -e "\n[Installation cancelled]"
		exit 1
	}
fi
echo -e "\n[Press ENTER to continue]"
read

#JSON server
clear
if [[ -e node_modules/.bin/json-server ]]; then
	echo "JSON Server already installed locally."
else
	echo -e "Creating a local installation of JSON server...\n"
	npm install json-server && {
		echo -e "\nDone."
	} || {
		echo "Unable to install json server (using npm)."
		echo "Maybe you do not have a correct Internet connection ?"
		echo -e "Trying to use 'npm install json-server' did not work."
		echo -e "\n[Installation cancelled]"
		exit 1
	}
fi
echo -e "\n[Press ENTER to continue]"
read

#remove install files
rm -f package.json
rm -f package-lock.json






# ---- VOICE WEB ----

#make sure user knows what to do
ok=""
while [[ $ok != 'y' ]]; do
	clear
	echo -e "We will now prepare the project installation.\n"
	echo -e "Please say 'yes' to all of the project requirements"
	echo -e "and select 'CSS' for default style format.\n"
	read -p "Is that ok ? [y/n] > " ok
done

#create a new Angular project
echo -e "\nCreating new Angular project...\n"
./node_modules/.bin/ng new VoiceWeb && {
	echo -e "\nDone."
} || {
	echo "Unable to create angular project."
	echo -e "Trying to use 'ng new VoiceWeb' did not work."
	echo -e "\n[Installation cancelled]"
	exit 1
}
echo -e "\n[Press ENTER to continue]"
read






# ---- GATHERING ----

#move the generated libraries into "Project" + move up "run" & "uninstall" + remove "install"
clear
echo "Reorganizing files & folders...\n"
mv VoiceWeb/node_modules Project/ && \
mv VoiceWeb/e2e Project/          && \
rm -rf VoiceWeb                   && \
mv Project/run $PWD               && \
mv Project/uninstall $PWD         && \
rm install                        && {
	echo -e "\nDone."
} || {
	echo "Unable to reorganize files correctly."
	echo -e "\n[Installation cancelled]"
	exit 1
}
echo -e "\n[Press ENTER to continue]"
read

#finished !
clear
echo -e "VoiceWeb installation has finished !\n"
echo "Enjoy !                I.A. & eerrtrr"
