#!/bin/bash



#remove VoiceWeb
rm -rf * && {
	echo "Successfully removed VoiceWeb files."
} || {
	echo "Unable to remove VoiceWeb files."
	echo "Maybe you have already removed it."
}
echo -e "\n[Press ENTER to continue]\n"
read



#finish
echo "Voice Web and all its components have been uninstalled"
